name: Ubuntu Image Builder

on:
  workflow_dispatch:

jobs:
  build:
    name: Build by ${{ github.actor }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create new repo
        run: |
          mkdir -p ~/work-dir
          mkdir -p ~/output-dir
          mkdir -p ~/ubuntu

          pushd ~/ubuntu

          sudo snap install ubuntu-image --classic
          cat <<EOF > amd64.yml
          name: ubuntu-amd64
          display-name: Ubuntu for amd64
          revision: 1
          architecture: amd64
          series: noble
          class: preinstalled

          kernel: linux-image-generic

          gadget:
            url: https://github.com/canonical/pc-gadget
            branch: classic
            type: git

          rootfs:
            components:
              - main
              - restricted
              - universe
              - multiverse
            archive: ubuntu
            mirror: http://archive.ubuntu.com/ubuntu/
            pocket: updates
            seed:
              urls:
                - git://git.launchpad.net/~ubuntu-core-dev/ubuntu-seeds/+git/
              names:
                - server
                - minimal
              branch: noble
              vcs: true
            sources-list-deb822: true

          customization:
            extra-snaps:
              - name: snapd

          artifacts:
            img:
              - name: ubuntu-amd64.img
            manifest:
              name: ubuntu-amd64.manifest
          EOF

          echo "Built with: $(ubuntu-image --version)" > disk.info
          echo "Built by: ${{ github.actor }}" >> disk.info
          echo "Time: $(date -u +"%b %d %Y")" >> disk.info
          echo "Gadget: 64bit PC Gadget Snap" >> disk.info

          sudo ubuntu-image --workdir ~/work-dir --output-dir ~/output-dir --disk-info ~/ubuntu/disk.info classic ~/ubuntu/amd64.yml

          sudo qemu-img convert -f raw -O vpc ~/output-dir/ubuntu-amd64.img ~/output-dir/ubuntu-amd64.iso

          mkdir -p ~/ubuntu-image-output
          cp ~/ubuntu/amd64.yml ~/ubuntu-image-output/
          cp ~/ubuntu/disk.info ~/ubuntu-image-output/
          cp ~/output-dir/ubuntu-amd64.img ~/ubuntu-image-output/
          cp ~/output-dir/ubuntu-amd64.iso ~/ubuntu-image-output/

          popd

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-build-output.zip
          path: ~/ubuntu-image-output/
          compression-level: 0
