name: Ubuntu Image Builder

on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Build and upload ubuntu image
        run: |
          mkdir -p ~/work-dir
          mkdir -p ~/output-dir
          mkdir -p ~/ubuntu

          pushd ~/ubuntu

          sudo snap install ubuntu-image --classic
          sudo apt update
          sudo apt install qemu-utils -y

          cat <<EOF > amd64.yml
          name: ubuntu-amd64
          display-name: Ubuntu for amd64
          revision: 1
          architecture: amd64
          series: noble
          class: preinstalled

          kernel: linux-image-generic

          gadget:
            url: https://github.com/canonical/pc-gadget
            branch: classic
            type: git

          rootfs:
            components:
              - main
              - restricted
              - universe
              - multiverse
            archive: ubuntu
            mirror: http://archive.ubuntu.com/ubuntu/
            pocket: updates
            seed:
              urls:
                - git://git.launchpad.net/~ubuntu-core-dev/ubuntu-seeds/+git/
              names:
                - server
                - minimal
              branch: noble
              vcs: true
            sources-list-deb822: true

          customization:
            extra-snaps:
              - name: snapd

          artifacts:
            img:
              - name: ubuntu-amd64.img
            manifest:
              name: ubuntu-amd64.manifest
          EOF

          echo "Built with: $(ubuntu-image --version)" > disk.info
          echo "Built by: ${{ github.actor }}" >> disk.info
          echo "Time: $(date -u +"%b %d %Y")" >> disk.info
          echo "Gadget: 64bit PC Gadget Snap" >> disk.info

          sudo ubuntu-image --workdir ~/work-dir --output-dir ~/output-dir --disk-info ~/ubuntu/disk.info classic ~/ubuntu/amd64.yml

          sudo qemu-img convert -f raw -O vpc ~/output-dir/ubuntu-amd64.img ~/output-dir/ubuntu-amd64.iso

          sudo qemu-img convert -f raw -O vpc -o subformat=fixed ~/output-dir/ubuntu-amd64.img ~/output-dir/ubuntu-amd64.vhd

          sudo truncate -s %1048576 ~/output-dir/ubuntu-amd64.img
          sudo truncate -s %1048576 ~/output-dir/ubuntu-amd64.iso
          sudo truncate -s %1048576 ~/output-dir/ubuntu-amd64.vhd

          mkdir -p ~/ubuntu-image-output
          cp ~/ubuntu/amd64.yml ~/ubuntu-image-output/
          cp ~/ubuntu/disk.info ~/ubuntu-image-output/
          cp ~/output-dir/ubuntu-amd64.img ~/ubuntu-image-output/
          cp ~/output-dir/ubuntu-amd64.iso ~/ubuntu-image-output/
          cp ~/output-dir/ubuntu-amd64.vhd ~/ubuntu-image-output/

          popd

          SUFFIX=$(echo $RANDOM | cut -c 1-5)
          RESOURCE_GROUP_NAME="ubuntu-image-${SUFFIX}-rg"
          STORAGE_ACCOUNT_NAME="ubuntuimage${SUFFIX}"
          az group create --name "${RESOURCE_GROUP_NAME}" --location "westus"
          az storage account create --name "${STORAGE_ACCOUNT_NAME}" --resource-group "${RESOURCE_GROUP_NAME}" --location "westus" --sku "Standard_LRS"
          az storage container create --name "edge" --account-name "${STORAGE_ACCOUNT_NAME}"

          CONNECTION_STRING=$(az storage account show-connection-string --resource-group "${RESOURCE_GROUP_NAME}" --name "${STORAGE_ACCOUNT_NAME}" --query connectionString --output tsv)

          az storage blob upload --account-name "${STORAGE_ACCOUNT_NAME}" --container-name "edge" --file "~/ubuntu-image-output/ubuntu-amd64.img" --connection-string "${CONNECTION_STRING}" --overwrite true
          az storage blob upload --account-name "${STORAGE_ACCOUNT_NAME}" --container-name "edge" --file "~/ubuntu-image-output/ubuntu-amd64.iso" --connection-string "${CONNECTION_STRING}" --overwrite true
          az storage blob upload --account-name "${STORAGE_ACCOUNT_NAME}" --container-name "edge" --file "~/ubuntu-image-output/ubuntu-amd64.vhd" --connection-string "${CONNECTION_STRING}" --overwrite true

          az image create --resource-group "${RESOURCE_GROUP_NAME}" --name ubuntu-custom-image --source https://${STORAGE_ACCOUNT_NAME}.blob.core.windows.net/edge/ubuntu-amd64.vhd --os-type Linux

          az vm create --resource-group "${RESOURCE_GROUP_NAME}" --name "ubuntu-custom-vm" --image ubuntu-custom-image --admin-username azureuser --generate-ssh-keys --size Standard_DS1_v2

      - name: Upload built artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-build-output.zip
          path: ~/ubuntu-image-output/
          compression-level: 0
